'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Announcements

    '''<summary>
    '''Announcements class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class Announcements

        '''<summary>
        '''canadeanNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents canadeanNews As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''hlAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAll As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hlGeneral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlGeneral As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hlSoftDrinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlSoftDrinks As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hlBeer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlBeer As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hlBeveragePackaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlBeveragePackaging As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hlDairyDrinks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlDairyDrinks As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''trFilterMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trFilterMonth As Global.System.Web.UI.HtmlControls.HtmlTableCell

        '''<summary>
        '''lblMonthYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMonthYear As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddMonthYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddMonthYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''canadeanEvents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents canadeanEvents As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''canadeanPressReleases control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents canadeanPressReleases As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCanadeanPressReleases control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCanadeanPressReleases As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSelection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelection As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlPressReleases control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPressReleases As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''viewtypeSelector control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents viewtypeSelector As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plSelectView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSelectView As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlViewType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlViewType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''litAnnouncements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAnnouncements As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''trRelatedProd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRelatedProd As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''phDE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDE As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''hlDataExtract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlDataExtract As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''hlDEBuyNow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlDEBuyNow As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''phReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phReport As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''hlReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlReport As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''litReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReport As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hlBuyNow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlBuyNow As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''phWisdom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phWisdom As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''gvResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvResults As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''tableSendToFriend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tableSendToFriend As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''tbYourName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbYourName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbTheirName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbTheirName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbYourEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbYourEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbTheirEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbTheirEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgBtnSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnSend As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''paging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents paging As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDebug As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
