'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Announcements

    '''<summary>
    '''EditAnnouncements class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class EditAnnouncements

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtPublishDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublishDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendar As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''valPublishDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPublishDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''valPublishDateRequired control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPublishDateRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtExpireDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpireDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendar2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendar2 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''valExpireDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valExpireDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''txtViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewOrder As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valViewOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valViewOrder As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
