'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Announcements


    Partial Public Class Settings

        '''<summary>
        '''plHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHistory As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHistory As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valHistory As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plDescriptionLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDescriptionLength As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDescriptionLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescriptionLength As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDescriptionLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDescriptionLength As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plHeaderTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeaderTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtHeaderTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeaderTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAltItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAltItemTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAltItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAltItemTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSeparator As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSeparator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeparator As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plFooterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFooterTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFooterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooterTemplate As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
